/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TownsRouteImport } from './routes/towns'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as TownSlugRouteImport } from './routes/$townSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RReferralSlugRouteImport } from './routes/r.$referralSlug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPacketsIndexRouteImport } from './routes/_authenticated/packets.index'
import { Route as AuthenticatedMeIndexRouteImport } from './routes/_authenticated/me.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPdfTownSlugRouteImport } from './routes/api/pdf.$townSlug'
import { Route as ApiPacketPdfSlugRouteImport } from './routes/api/packet-pdf.$slug'
import { Route as AuthenticatedPacketsNewRouteImport } from './routes/_authenticated/packets.new'
import { Route as AuthenticatedPacketsIdRouteImport } from './routes/_authenticated/packets.$id'
import { Route as AuthenticatedMeWelcomeRouteImport } from './routes/_authenticated/me.welcome'
import { Route as AuthenticatedMeSettingsRouteImport } from './routes/_authenticated/me.settings'
import { Route as AuthenticatedMeSavedRouteImport } from './routes/_authenticated/me.saved'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminRealtorsRouteImport } from './routes/_authenticated/admin.realtors'
import { Route as AuthenticatedAdminInviteCodesRouteImport } from './routes/_authenticated/admin.invite-codes'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'

const TownsRoute = TownsRouteImport.update({
  id: '/towns',
  path: '/towns',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TownSlugRoute = TownSlugRouteImport.update({
  id: '/$townSlug',
  path: '/$townSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RReferralSlugRoute = RReferralSlugRouteImport.update({
  id: '/r/$referralSlug',
  path: '/r/$referralSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacketsIndexRoute =
  AuthenticatedPacketsIndexRouteImport.update({
    id: '/packets/',
    path: '/packets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeIndexRoute = AuthenticatedMeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPdfTownSlugRoute = ApiPdfTownSlugRouteImport.update({
  id: '/api/pdf/$townSlug',
  path: '/api/pdf/$townSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacketPdfSlugRoute = ApiPacketPdfSlugRouteImport.update({
  id: '/api/packet-pdf/$slug',
  path: '/api/packet-pdf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPacketsNewRoute = AuthenticatedPacketsNewRouteImport.update({
  id: '/packets/new',
  path: '/packets/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacketsIdRoute = AuthenticatedPacketsIdRouteImport.update({
  id: '/packets/$id',
  path: '/packets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeWelcomeRoute = AuthenticatedMeWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedMeSettingsRoute = AuthenticatedMeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedMeSavedRoute = AuthenticatedMeSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedMeRoute,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRealtorsRoute =
  AuthenticatedAdminRealtorsRouteImport.update({
    id: '/realtors',
    path: '/realtors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInviteCodesRoute =
  AuthenticatedAdminInviteCodesRouteImport.update({
    id: '/invite-codes',
    path: '/invite-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$townSlug': typeof TownSlugRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/towns': typeof TownsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$referralSlug': typeof RReferralSlugRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/invite-codes': typeof AuthenticatedAdminInviteCodesRoute
  '/admin/realtors': typeof AuthenticatedAdminRealtorsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/me/saved': typeof AuthenticatedMeSavedRoute
  '/me/settings': typeof AuthenticatedMeSettingsRoute
  '/me/welcome': typeof AuthenticatedMeWelcomeRoute
  '/packets/$id': typeof AuthenticatedPacketsIdRoute
  '/packets/new': typeof AuthenticatedPacketsNewRoute
  '/api/packet-pdf/$slug': typeof ApiPacketPdfSlugRoute
  '/api/pdf/$townSlug': typeof ApiPdfTownSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/me/': typeof AuthenticatedMeIndexRoute
  '/packets/': typeof AuthenticatedPacketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$townSlug': typeof TownSlugRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/towns': typeof TownsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$referralSlug': typeof RReferralSlugRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/invite-codes': typeof AuthenticatedAdminInviteCodesRoute
  '/admin/realtors': typeof AuthenticatedAdminRealtorsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/me/saved': typeof AuthenticatedMeSavedRoute
  '/me/settings': typeof AuthenticatedMeSettingsRoute
  '/me/welcome': typeof AuthenticatedMeWelcomeRoute
  '/packets/$id': typeof AuthenticatedPacketsIdRoute
  '/packets/new': typeof AuthenticatedPacketsNewRoute
  '/api/packet-pdf/$slug': typeof ApiPacketPdfSlugRoute
  '/api/pdf/$townSlug': typeof ApiPdfTownSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/me': typeof AuthenticatedMeIndexRoute
  '/packets': typeof AuthenticatedPacketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$townSlug': typeof TownSlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/towns': typeof TownsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/me': typeof AuthenticatedMeRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$referralSlug': typeof RReferralSlugRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/invite-codes': typeof AuthenticatedAdminInviteCodesRoute
  '/_authenticated/admin/realtors': typeof AuthenticatedAdminRealtorsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/me/saved': typeof AuthenticatedMeSavedRoute
  '/_authenticated/me/settings': typeof AuthenticatedMeSettingsRoute
  '/_authenticated/me/welcome': typeof AuthenticatedMeWelcomeRoute
  '/_authenticated/packets/$id': typeof AuthenticatedPacketsIdRoute
  '/_authenticated/packets/new': typeof AuthenticatedPacketsNewRoute
  '/api/packet-pdf/$slug': typeof ApiPacketPdfSlugRoute
  '/api/pdf/$townSlug': typeof ApiPdfTownSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/me/': typeof AuthenticatedMeIndexRoute
  '/_authenticated/packets/': typeof AuthenticatedPacketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$townSlug'
    | '/about'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/towns'
    | '/admin'
    | '/dashboard'
    | '/me'
    | '/settings'
    | '/p/$slug'
    | '/r/$referralSlug'
    | '/admin/events'
    | '/admin/invite-codes'
    | '/admin/realtors'
    | '/admin/subscribers'
    | '/me/saved'
    | '/me/settings'
    | '/me/welcome'
    | '/packets/$id'
    | '/packets/new'
    | '/api/packet-pdf/$slug'
    | '/api/pdf/$townSlug'
    | '/admin/'
    | '/me/'
    | '/packets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$townSlug'
    | '/about'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/towns'
    | '/dashboard'
    | '/settings'
    | '/p/$slug'
    | '/r/$referralSlug'
    | '/admin/events'
    | '/admin/invite-codes'
    | '/admin/realtors'
    | '/admin/subscribers'
    | '/me/saved'
    | '/me/settings'
    | '/me/welcome'
    | '/packets/$id'
    | '/packets/new'
    | '/api/packet-pdf/$slug'
    | '/api/pdf/$townSlug'
    | '/admin'
    | '/me'
    | '/packets'
  id:
    | '__root__'
    | '/'
    | '/$townSlug'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/towns'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/me'
    | '/_authenticated/settings'
    | '/p/$slug'
    | '/r/$referralSlug'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/invite-codes'
    | '/_authenticated/admin/realtors'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/me/saved'
    | '/_authenticated/me/settings'
    | '/_authenticated/me/welcome'
    | '/_authenticated/packets/$id'
    | '/_authenticated/packets/new'
    | '/api/packet-pdf/$slug'
    | '/api/pdf/$townSlug'
    | '/_authenticated/admin/'
    | '/_authenticated/me/'
    | '/_authenticated/packets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TownSlugRoute: typeof TownSlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TownsRoute: typeof TownsRoute
  PSlugRoute: typeof PSlugRoute
  RReferralSlugRoute: typeof RReferralSlugRoute
  ApiPacketPdfSlugRoute: typeof ApiPacketPdfSlugRoute
  ApiPdfTownSlugRoute: typeof ApiPdfTownSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/towns': {
      id: '/towns'
      path: '/towns'
      fullPath: '/towns'
      preLoaderRoute: typeof TownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$townSlug': {
      id: '/$townSlug'
      path: '/$townSlug'
      fullPath: '/$townSlug'
      preLoaderRoute: typeof TownSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$referralSlug': {
      id: '/r/$referralSlug'
      path: '/r/$referralSlug'
      fullPath: '/r/$referralSlug'
      preLoaderRoute: typeof RReferralSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packets/': {
      id: '/_authenticated/packets/'
      path: '/packets'
      fullPath: '/packets/'
      preLoaderRoute: typeof AuthenticatedPacketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/': {
      id: '/_authenticated/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticatedMeIndexRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/pdf/$townSlug': {
      id: '/api/pdf/$townSlug'
      path: '/api/pdf/$townSlug'
      fullPath: '/api/pdf/$townSlug'
      preLoaderRoute: typeof ApiPdfTownSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packet-pdf/$slug': {
      id: '/api/packet-pdf/$slug'
      path: '/api/packet-pdf/$slug'
      fullPath: '/api/packet-pdf/$slug'
      preLoaderRoute: typeof ApiPacketPdfSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/packets/new': {
      id: '/_authenticated/packets/new'
      path: '/packets/new'
      fullPath: '/packets/new'
      preLoaderRoute: typeof AuthenticatedPacketsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packets/$id': {
      id: '/_authenticated/packets/$id'
      path: '/packets/$id'
      fullPath: '/packets/$id'
      preLoaderRoute: typeof AuthenticatedPacketsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/welcome': {
      id: '/_authenticated/me/welcome'
      path: '/welcome'
      fullPath: '/me/welcome'
      preLoaderRoute: typeof AuthenticatedMeWelcomeRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/settings': {
      id: '/_authenticated/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof AuthenticatedMeSettingsRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/me/saved': {
      id: '/_authenticated/me/saved'
      path: '/saved'
      fullPath: '/me/saved'
      preLoaderRoute: typeof AuthenticatedMeSavedRouteImport
      parentRoute: typeof AuthenticatedMeRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/realtors': {
      id: '/_authenticated/admin/realtors'
      path: '/realtors'
      fullPath: '/admin/realtors'
      preLoaderRoute: typeof AuthenticatedAdminRealtorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invite-codes': {
      id: '/_authenticated/admin/invite-codes'
      path: '/invite-codes'
      fullPath: '/admin/invite-codes'
      preLoaderRoute: typeof AuthenticatedAdminInviteCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminInviteCodesRoute: typeof AuthenticatedAdminInviteCodesRoute
  AuthenticatedAdminRealtorsRoute: typeof AuthenticatedAdminRealtorsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminInviteCodesRoute: AuthenticatedAdminInviteCodesRoute,
  AuthenticatedAdminRealtorsRoute: AuthenticatedAdminRealtorsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMeRouteChildren {
  AuthenticatedMeSavedRoute: typeof AuthenticatedMeSavedRoute
  AuthenticatedMeSettingsRoute: typeof AuthenticatedMeSettingsRoute
  AuthenticatedMeWelcomeRoute: typeof AuthenticatedMeWelcomeRoute
  AuthenticatedMeIndexRoute: typeof AuthenticatedMeIndexRoute
}

const AuthenticatedMeRouteChildren: AuthenticatedMeRouteChildren = {
  AuthenticatedMeSavedRoute: AuthenticatedMeSavedRoute,
  AuthenticatedMeSettingsRoute: AuthenticatedMeSettingsRoute,
  AuthenticatedMeWelcomeRoute: AuthenticatedMeWelcomeRoute,
  AuthenticatedMeIndexRoute: AuthenticatedMeIndexRoute,
}

const AuthenticatedMeRouteWithChildren = AuthenticatedMeRoute._addFileChildren(
  AuthenticatedMeRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPacketsIdRoute: typeof AuthenticatedPacketsIdRoute
  AuthenticatedPacketsNewRoute: typeof AuthenticatedPacketsNewRoute
  AuthenticatedPacketsIndexRoute: typeof AuthenticatedPacketsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeRoute: AuthenticatedMeRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPacketsIdRoute: AuthenticatedPacketsIdRoute,
  AuthenticatedPacketsNewRoute: AuthenticatedPacketsNewRoute,
  AuthenticatedPacketsIndexRoute: AuthenticatedPacketsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TownSlugRoute: TownSlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TownsRoute: TownsRoute,
  PSlugRoute: PSlugRoute,
  RReferralSlugRoute: RReferralSlugRoute,
  ApiPacketPdfSlugRoute: ApiPacketPdfSlugRoute,
  ApiPdfTownSlugRoute: ApiPdfTownSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
