/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TownsRouteImport } from './routes/towns'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as TownSlugRouteImport } from './routes/$townSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RReferralSlugRouteImport } from './routes/r.$referralSlug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPacketsIndexRouteImport } from './routes/_authenticated/packets.index'
import { Route as ApiPdfTownSlugRouteImport } from './routes/api/pdf.$townSlug'
import { Route as ApiPacketPdfSlugRouteImport } from './routes/api/packet-pdf.$slug'
import { Route as AuthenticatedPacketsNewRouteImport } from './routes/_authenticated/packets.new'
import { Route as AuthenticatedPacketsIdRouteImport } from './routes/_authenticated/packets.$id'

const TownsRoute = TownsRouteImport.update({
  id: '/towns',
  path: '/towns',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TownSlugRoute = TownSlugRouteImport.update({
  id: '/$townSlug',
  path: '/$townSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RReferralSlugRoute = RReferralSlugRouteImport.update({
  id: '/r/$referralSlug',
  path: '/r/$referralSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacketsIndexRoute =
  AuthenticatedPacketsIndexRouteImport.update({
    id: '/packets/',
    path: '/packets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPdfTownSlugRoute = ApiPdfTownSlugRouteImport.update({
  id: '/api/pdf/$townSlug',
  path: '/api/pdf/$townSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacketPdfSlugRoute = ApiPacketPdfSlugRouteImport.update({
  id: '/api/packet-pdf/$slug',
  path: '/api/packet-pdf/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPacketsNewRoute = AuthenticatedPacketsNewRouteImport.update({
  id: '/packets/new',
  path: '/packets/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacketsIdRoute = AuthenticatedPacketsIdRouteImport.update({
  id: '/packets/$id',
  path: '/packets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$townSlug': typeof TownSlugRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/towns': typeof TownsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$referralSlug': typeof RReferralSlugRoute
  '/packets/$id': typeof AuthenticatedPacketsIdRoute
  '/packets/new': typeof AuthenticatedPacketsNewRoute
  '/api/packet-pdf/$slug': typeof ApiPacketPdfSlugRoute
  '/api/pdf/$townSlug': typeof ApiPdfTownSlugRoute
  '/packets/': typeof AuthenticatedPacketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$townSlug': typeof TownSlugRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/towns': typeof TownsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$referralSlug': typeof RReferralSlugRoute
  '/packets/$id': typeof AuthenticatedPacketsIdRoute
  '/packets/new': typeof AuthenticatedPacketsNewRoute
  '/api/packet-pdf/$slug': typeof ApiPacketPdfSlugRoute
  '/api/pdf/$townSlug': typeof ApiPdfTownSlugRoute
  '/packets': typeof AuthenticatedPacketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$townSlug': typeof TownSlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/towns': typeof TownsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$referralSlug': typeof RReferralSlugRoute
  '/_authenticated/packets/$id': typeof AuthenticatedPacketsIdRoute
  '/_authenticated/packets/new': typeof AuthenticatedPacketsNewRoute
  '/api/packet-pdf/$slug': typeof ApiPacketPdfSlugRoute
  '/api/pdf/$townSlug': typeof ApiPdfTownSlugRoute
  '/_authenticated/packets/': typeof AuthenticatedPacketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$townSlug'
    | '/about'
    | '/login'
    | '/towns'
    | '/dashboard'
    | '/settings'
    | '/p/$slug'
    | '/r/$referralSlug'
    | '/packets/$id'
    | '/packets/new'
    | '/api/packet-pdf/$slug'
    | '/api/pdf/$townSlug'
    | '/packets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$townSlug'
    | '/about'
    | '/login'
    | '/towns'
    | '/dashboard'
    | '/settings'
    | '/p/$slug'
    | '/r/$referralSlug'
    | '/packets/$id'
    | '/packets/new'
    | '/api/packet-pdf/$slug'
    | '/api/pdf/$townSlug'
    | '/packets'
  id:
    | '__root__'
    | '/'
    | '/$townSlug'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/towns'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/p/$slug'
    | '/r/$referralSlug'
    | '/_authenticated/packets/$id'
    | '/_authenticated/packets/new'
    | '/api/packet-pdf/$slug'
    | '/api/pdf/$townSlug'
    | '/_authenticated/packets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TownSlugRoute: typeof TownSlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  TownsRoute: typeof TownsRoute
  PSlugRoute: typeof PSlugRoute
  RReferralSlugRoute: typeof RReferralSlugRoute
  ApiPacketPdfSlugRoute: typeof ApiPacketPdfSlugRoute
  ApiPdfTownSlugRoute: typeof ApiPdfTownSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/towns': {
      id: '/towns'
      path: '/towns'
      fullPath: '/towns'
      preLoaderRoute: typeof TownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$townSlug': {
      id: '/$townSlug'
      path: '/$townSlug'
      fullPath: '/$townSlug'
      preLoaderRoute: typeof TownSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$referralSlug': {
      id: '/r/$referralSlug'
      path: '/r/$referralSlug'
      fullPath: '/r/$referralSlug'
      preLoaderRoute: typeof RReferralSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packets/': {
      id: '/_authenticated/packets/'
      path: '/packets'
      fullPath: '/packets/'
      preLoaderRoute: typeof AuthenticatedPacketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/pdf/$townSlug': {
      id: '/api/pdf/$townSlug'
      path: '/api/pdf/$townSlug'
      fullPath: '/api/pdf/$townSlug'
      preLoaderRoute: typeof ApiPdfTownSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packet-pdf/$slug': {
      id: '/api/packet-pdf/$slug'
      path: '/api/packet-pdf/$slug'
      fullPath: '/api/packet-pdf/$slug'
      preLoaderRoute: typeof ApiPacketPdfSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/packets/new': {
      id: '/_authenticated/packets/new'
      path: '/packets/new'
      fullPath: '/packets/new'
      preLoaderRoute: typeof AuthenticatedPacketsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packets/$id': {
      id: '/_authenticated/packets/$id'
      path: '/packets/$id'
      fullPath: '/packets/$id'
      preLoaderRoute: typeof AuthenticatedPacketsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPacketsIdRoute: typeof AuthenticatedPacketsIdRoute
  AuthenticatedPacketsNewRoute: typeof AuthenticatedPacketsNewRoute
  AuthenticatedPacketsIndexRoute: typeof AuthenticatedPacketsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPacketsIdRoute: AuthenticatedPacketsIdRoute,
  AuthenticatedPacketsNewRoute: AuthenticatedPacketsNewRoute,
  AuthenticatedPacketsIndexRoute: AuthenticatedPacketsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TownSlugRoute: TownSlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  TownsRoute: TownsRoute,
  PSlugRoute: PSlugRoute,
  RReferralSlugRoute: RReferralSlugRoute,
  ApiPacketPdfSlugRoute: ApiPacketPdfSlugRoute,
  ApiPdfTownSlugRoute: ApiPdfTownSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
